[MPIPreferences]
_format = "1.1"
abi = "MPICH"
binary = "system"
cclibs = ["pmi", "pmi2", "pthread", "pals", "rt", "pthread", "pmi", "pmi2"]
libmpi = "libmpi_nvidia.so"
mpiexec = "mpiexec"
preloads = ["libmpi_gtl_cuda.so"]
preloads_env_switch = "MPICH_GPU_SUPPORT_ENABLED"
